branch-defaults:
  default:
    environment: battery-soh-env
    group_suffix: null
environment-defaults:
  battery-soh-env:
    branch: null
    repository: null
global:
  application_name: battery-soh-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
